### ISSUE TITLE
这个太赞了! 开个帖来夸夸作者!

### ISSUE THREAD

**Issue by makerjackie** [ImBearChild/SiplPen#2]
而且UI比: https://github.com/PeggyZWY/flowstate-webapp 这个更好，用起来很舒服

不知道这个 心流模式 vscode有没有相应的插件

**Comment by ImBearChild** [comment]
谢谢您的称赞！😄

**Comment by makerjackie** [comment]
有没赞赏码，给你来个咖啡哈哈哈

**Comment by ImBearChild** [comment]
啊哈，咖啡就免了，有这份心意就够。况且我能做出这个，完全是站在巨人的肩膀上。 :D

**Comment by makerjackie** [comment]
哈哈哈好，补个给我这种小白的本机安装说明: 

```
sudo apt install npm
npm install http-server -g
cd src
http-server
```
